---

- name: install svacer
  hosts: "{{ target | default('local')  }}"
  become: true
  vars_file:
    - vars.yml

  roles:
    - role: environment_preparation
      tags:
        - always

    - role: add_docker_repo
      when: ansible_distribution == "Debian"

    - role: svacer_server_launch
      tags:
        - always
    