---

- name: add remote host to inventory
  hosts: localhost
  tasks:
    - name: add host
      ansible.builtin.add_host:
        name: "{{ target }}"
        groups: all
      when: target != 'localhost'

- name: install svacer
  hosts: "{{ target | default('localhost')  }}"
  become: true
  vars_files:
    - vars.yml
  roles:
    - role: set_sec
      tags:
        - prod

    - role: add_docker_repo
      tags:
        - always

    - role: environment_preparation
      tags:
        - always

    - role: svacer_server_launch
      tags:
        - always
    