---

- name: make docker group
  ansible.builtin.group:
    name: docker
    state: present

- name: make docker user
  ansible.builtin.user:
    name: docker
    shell: /bin/bash
    group: docker
    create_home: yes

- name: get passwd database
  ansible.builtin.getent:
    database: passwd

- name: append USER to docker group
  ansible.builtin.user:
    name: "{{ main_user }}"
    groups: docker
    append: yes
  when: 
    - main_user is defined
    - main_user in getent_passwd

- name: install general req packages
  ansible.builtin.apt: 
    name: 
      - ca-certificates
      - curl
      - docker-ce-cli
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: install service req packages
  ansible.builtin.apt: 
    name:
      - containerd.io
      - docker-ce
    state: present
  notify: Restart docker services

- name: make dir for svacer-server
  ansible.builtin.file:
    path: "{{ svacer_server_dir }}"
    state: directory
    mode: '0755'

- name: download docker compose svacer
  ansible.builtin.get_url:
    url: https://svacer.ispras.ru/extra/docker-compose.yml
    dest: "{{ svacer_server_dir }}/docker-compose.yml"
    mode: '0644'