---

- name: launch svacer-server
  community.docker.docker_compose_v2:
    project_src: "{{ svacer_server_dir }}"
    state: present
  register: status_launch_svacer
  until: status_launch_svacer is success
  retries: 40
  delay: 2