---

- name: ca-certificates
  ansible.builtin.apt: 
    name: ca-certificates
    state: present

- name: make dir keyrings
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: add docker gpg for debian

